# Generated by Django 3.2.8 on 2021-11-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='image_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='listings', to='auctions.Category'),
        ),
    ]
