# Generated by Django 3.2.8 on 2021-11-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listing_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
